name: My First Workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: checkout repo
              uses: actions/checkout@v4

            - name: List and Read files
              run: |      
                echo "My First Github Job" 
                ls -ltra
                cat README.md

            - name: Generate ASCII Artwork
              run: cowsay - dragon "Run for cover, I'm a DRAGON....RAWE" >> gragon.txt
            # - name: List files
            #   run: ls
            # - name: Read file
            #   run: cat README.md