name: Generate Ascii Artwork

on: push

jobs:
    ascii_job:
        runs-on: ubuntu-latest
        steps:
            - name: checkout repo
              uses: actions/checkout@v4

            - name: Install Cowsay program
              run: sudo apt-get install cowsay -y

            - name: Execute CowSay CMD
              run: cowsay - dragon "Run for cover, I'm a DRAGON....RAWE" >> gragon.txt
            
            - name: Test File exists
              run: grep -i "dragon" gragon.txt
            
            - name: Read File
              run: cat gragon.txt
            
            - name: List Repo files
              run: ls -ltra