name: Workflow filters

on:
    workflow_dispatch: 
    push:
        branches-ignore: 
            - feature/*
            - test/**
        branches: 
            - main
            - '!feature/*' #Ignore workflow run when pushing to any branch name starting with feature
    
    pull_request: 
        types: 
            - opened
            - closed
        paths-ignore: 
            - README.md
        branches: 
            - main
jobs:
    hello:
        runs-on: ubuntu-latest
        steps:
            - run: echo 'Hello World'